markdown: kramdown
permalink: /:title/
url: https://hansenbeast.github.io/
name: Hansenbeast.Net
author: Hansenbeast
email: wangzehao1998@126.com
github: Hansenbeast
safe: true
paginate: 20
about: "这里是 Hansenbeast 的个人博客。"